<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2yy5xfg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2yy5xfg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2yy5xfg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2yy5xfg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2yy5xfg\appDevDebugProjectContainer([
    'container.build_hash' => '2yy5xfg',
    'container.build_id' => 'd3558ad9',
    'container.build_time' => 1652310709,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2yy5xfg');
