<?php

namespace backOfficeBundle\Repository;

/**
 * attribute_colorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attribute_colorRepository extends \Doctrine\ORM\EntityRepository
{
}
