<?php

namespace backOfficeBundle\Repository;

/**
 * chargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chargeRepository extends \Doctrine\ORM\EntityRepository
{
}
