<?php

namespace backOfficeBundle\Repository;

/**
 * color_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class color_productRepository extends \Doctrine\ORM\EntityRepository
{
}
