<?php

namespace backOfficeBundle\Repository;

/**
 * depenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class depenceRepository extends \Doctrine\ORM\EntityRepository
{
}
