<?php

namespace backOfficeBundle\Repository;

/**
 * Detail_StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_StockRepository extends \Doctrine\ORM\EntityRepository
{
}
