<?php

namespace backOfficeBundle\Repository;

/**
 * Detail_projetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_projetRepository extends \Doctrine\ORM\EntityRepository
{
}
