<?php

namespace backOfficeBundle\Repository;

/**
 * detail_factureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detail_factureRepository extends \Doctrine\ORM\EntityRepository
{
}
