<?php

namespace backOfficeBundle\Repository;

/**
 * facturefournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class facturefournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
