<?php

namespace backOfficeBundle\Repository;

/**
 * listRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
