<?php

namespace backOfficeBundle\Repository;

/**
 * numeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class numeroRepository extends \Doctrine\ORM\EntityRepository
{
}
