<?php

namespace backOfficeBundle\Repository;

/**
 * paimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paimentRepository extends \Doctrine\ORM\EntityRepository
{
}
