<?php

namespace backOfficeBundle\Repository;

/**
 * piecejointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class piecejointRepository extends \Doctrine\ORM\EntityRepository
{
}
