<?php

namespace backOfficeBundle\Repository;

/**
 * produitstockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitstockRepository extends \Doctrine\ORM\EntityRepository
{
}
