<?php

namespace backOfficeBundle\Repository;

/**
 * produitsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
