<?php

namespace backOfficeBundle\Repository;

/**
 * Produit_StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_StockRepository extends \Doctrine\ORM\EntityRepository
{
}
