<?php

namespace backOfficeBundle\Repository;

/**
 * produit_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produit_infoRepository extends \Doctrine\ORM\EntityRepository
{
}
