<?php

namespace backOfficeBundle\Repository;

/**
 * ProduitpremierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitpremierRepository extends \Doctrine\ORM\EntityRepository
{
}
