<?php

namespace backOfficeBundle\Repository;

/**
 * siteWebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class siteWebRepository extends \Doctrine\ORM\EntityRepository
{
}
