<?php

namespace backOfficeBundle\Repository;

/**
 * sliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sliderRepository extends \Doctrine\ORM\EntityRepository
{
}
