<?php

namespace backOfficeBundle\Repository;

/**
 * souscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class souscategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
