<?php

namespace backOfficeBundle\Repository;

/**
 * TaillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaillesRepository extends \Doctrine\ORM\EntityRepository
{
}
