<?php

namespace backOfficeBundle\Repository;

/**
 * tokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tokenRepository extends \Doctrine\ORM\EntityRepository
{
}
