<?php

namespace backOfficeBundle\Repository;

/**
 * video_sliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class video_sliderRepository extends \Doctrine\ORM\EntityRepository
{
}
